title: Quinte Hackathon - Fall 2024
description: An upcoming Hackathon for the Quinte
baseurl: "https://quintehackathon.github.io/2024-fall/"
url: https://quintehackathon.github.io/2024-fall

theme: jekyll-nagymaros

copyright: Place Holder
indexing: true

permalink: pretty

exclude:
  - LICENSE
  - README.md
